#include "gs/ply_io.h"

#include <cstdio>
#include <cstring>
#include <vector>

namespace splatscan {

namespace {

bool readLine(FILE* file, std::string& out) {
    out.clear();
    int value = 0;
    while ((value = std::fgetc(file)) != EOF) {
        if (value == '\n') return true;
        out.push_back(static_cast<char>(value));
    }
    return !out.empty();
}

}  // namespace

bool readPlyModel(const std::string& path, GaussianParams& out, Vec3& boundsCenter,
                  float& boundsRadius) {
    FILE* file = std::fopen(path.c_str(), "rb");
    if (file == nullptr) return false;

    std::string line;
    if (!readLine(file, line) || line.rfind("ply", 0) != 0) {
        std::fclose(file);
        return false;
    }

    int32_t vertexCount = 0;
    bool binaryLittleEndian = false;
    while (readLine(file, line)) {
        if (line.rfind("format", 0) == 0) {
            binaryLittleEndian = line.find("binary_little_endian") != std::string::npos;
        } else if (line.rfind("element vertex", 0) == 0) {
            vertexCount = std::atoi(line.c_str() + 14);
        } else if (line.rfind("end_header", 0) == 0) {
            break;
        }
    }

    if (!binaryLittleEndian || vertexCount <= 0) {
        std::fclose(file);
        return false;
    }

    out.ensureCapacity(vertexCount);

    float minX = 1e30f;
    float minY = 1e30f;
    float minZ = 1e30f;
    float maxX = -1e30f;
    float maxY = -1e30f;
    float maxZ = -1e30f;

    std::vector<float> buffer(kPlyPropertyCount);
    for (int32_t i = 0; i < vertexCount; ++i) {
        if (std::fread(buffer.data(), sizeof(float), kPlyPropertyCount, file) !=
            static_cast<size_t>(kPlyPropertyCount)) {
            break;
        }
        // 属性顺序只在 ply_io.h 的 PlyProperty 里定义一次
        const float px = buffer[kPlyX];
        const float py = buffer[kPlyY];
        const float pz = buffer[kPlyZ];
        const float red = buffer[kPlyRed];
        const float green = buffer[kPlyGreen];
        const float blue = buffer[kPlyBlue];
        const float opacity = buffer[kPlyOpacity];
        const float scaleX = buffer[kPlyScale0];
        const float scaleY = buffer[kPlyScale1];

        out.add({px, py, pz}, scaleX, scaleY, {red, green, blue}, opacity);

        minX = px < minX ? px : minX;
        minY = py < minY ? py : minY;
        minZ = pz < minZ ? pz : minZ;
        maxX = px > maxX ? px : maxX;
        maxY = py > maxY ? py : maxY;
        maxZ = pz > maxZ ? pz : maxZ;
    }
    std::fclose(file);

    boundsCenter = {(minX + maxX) * 0.5f, (minY + maxY) * 0.5f, (minZ + maxZ) * 0.5f};
    const float dx = maxX - minX;
    const float dy = maxY - minY;
    const float dz = maxZ - minZ;
    const float diagonal = std::sqrt(dx * dx + dy * dy + dz * dz);
    boundsRadius = diagonal > 1e-3f ? diagonal * 0.5f : 1.0f;
    return out.count > 0;
}

bool writePlyModel(const std::string& path, const GaussianParams& model) {
    FILE* file = std::fopen(path.c_str(), "wb");
    if (file == nullptr) return false;

    std::fprintf(file,
                 "ply\nformat binary_little_endian 1.0\ncomment Generated by SplatScan\n"
                 "element vertex %d\n"
                 "property float x\nproperty float y\nproperty float z\n"
                 "property float nx\nproperty float ny\nproperty float nz\n"
                 "property float f_dc_0\nproperty float f_dc_1\nproperty float f_dc_2\n"
                 "property float opacity\n"
                 "property float scale_0\nproperty float scale_1\nproperty float scale_2\n"
                 "property float rot_0\nproperty float rot_1\nproperty float rot_2\n"
                 "property float rot_3\nend_header\n",
                 model.count);

    float values[kPlyPropertyCount] = {0.0f};
    for (int32_t i = 0; i < model.count; ++i) {
        values[kPlyX] = model.position[i * 3 + 0];
        values[kPlyY] = model.position[i * 3 + 1];
        values[kPlyZ] = model.position[i * 3 + 2];
        values[kPlyRed] = model.color[i * 3 + 0];
        values[kPlyGreen] = model.color[i * 3 + 1];
        values[kPlyBlue] = model.color[i * 3 + 2];
        values[kPlyOpacity] = model.opacity[i];
        values[kPlyScale0] = model.logScale[i * 2 + 0];
        values[kPlyScale1] = model.logScale[i * 2 + 1];
        values[kPlyScale2] = model.logScale[i * 2 + 1];
        values[kPlyRot0] = 1.0f;
        values[kPlyRot1] = 0.0f;
        values[kPlyRot2] = 0.0f;
        values[kPlyRot3] = 0.0f;
        std::fwrite(values, sizeof(float), kPlyPropertyCount, file);
    }
    std::fclose(file);
    return true;
}

}  // namespace splatscan