package com.splatscan.app.format

import java.io.BufferedInputStream
import java.io.BufferedOutputStream
import java.io.EOFException
import java.io.InputStream
import java.io.OutputStream
import java.nio.ByteBuffer
import java.nio.ByteOrder

/**
 * 3D 高斯泼溅的二进制 PLY 读写。
 *
 * 采用通用约定：17 个 float 属性（位置、法线占位、球谐 DC 三通道、不透明度 logit、
 * 对数尺度三通道、四元数四通道），小端序，属性顺序固定。这样文件能被桌面端工具直接打开。
 */
object PlyCodec {

    private const val PROPERTY_COUNT = 17

    private val header = buildString {
        append("ply\n")
        append("format binary_little_endian 1.0\n")
        append("comment Generated by SplatScan\n")
        append("element vertex %d\n")
        append("property float x\n")
        append("property float y\n")
        append("property float z\n")
        append("property float nx\n")
        append("property float ny\n")
        append("property float nz\n")
        append("property float f_dc_0\n")
        append("property float f_dc_1\n")
        append("property float f_dc_2\n")
        append("property float opacity\n")
        append("property float scale_0\n")
        append("property float scale_1\n")
        append("property float scale_2\n")
        append("property float rot_0\n")
        append("property float rot_1\n")
        append("property float rot_2\n")
        append("property float rot_3\n")
        append("end_header\n")
    }

    fun write(cloud: GaussianCloud, output: OutputStream) {
        val stream = BufferedOutputStream(output, 1 shl 16)
        stream.write(String.format(header, cloud.count).toByteArray(Charsets.US_ASCII))
        val buffer = ByteBuffer.allocate(PROPERTY_COUNT * 4).order(ByteOrder.LITTLE_ENDIAN)
        for (i in 0 until cloud.count) {
            buffer.clear()
            val p = i * 3
            val q = i * 4
            buffer.putFloat(cloud.positions[p])
            buffer.putFloat(cloud.positions[p + 1])
            buffer.putFloat(cloud.positions[p + 2])
            buffer.putFloat(0f)
            buffer.putFloat(0f)
            buffer.putFloat(0f)
            buffer.putFloat(cloud.colors[p])
            buffer.putFloat(cloud.colors[p + 1])
            buffer.putFloat(cloud.colors[p + 2])
            buffer.putFloat(cloud.opacities[i])
            buffer.putFloat(cloud.scales[p])
            buffer.putFloat(cloud.scales[p + 1])
            buffer.putFloat(cloud.scales[p + 2])
            buffer.putFloat(cloud.rotations[q])
            buffer.putFloat(cloud.rotations[q + 1])
            buffer.putFloat(cloud.rotations[q + 2])
            buffer.putFloat(cloud.rotations[q + 3])
            stream.write(buffer.array(), 0, PROPERTY_COUNT * 4)
        }
        stream.flush()
    }

    fun read(input: InputStream): GaussianCloud {
        val stream = BufferedInputStream(input, 1 shl 16)
        val headerBytes = StringBuilder()
        var count = 0
        while (true) {
            val line = readLine(stream) ?: throw EOFException("PLY 头不完整")
            headerBytes.append(line).append('\n')
            if (line.startsWith("element vertex ")) {
                count = line.removePrefix("element vertex ").trim().toInt()
            }
            if (line.trim() == "end_header") break
        }
        val cloud = GaussianCloud(count.coerceAtLeast(1))
        val buffer = ByteArray(PROPERTY_COUNT * 4)
        for (i in 0 until count) {
            readFully(stream, buffer)
            val bb = ByteBuffer.wrap(buffer).order(ByteOrder.LITTLE_ENDIAN)
            val px = bb.float
            val py = bb.float
            val pz = bb.float
            bb.float
            bb.float
            bb.float
            val r = bb.float
            val g = bb.float
            val b = bb.float
            val opacity = bb.float
            val sx = bb.float
            val sy = bb.float
            val sz = bb.float
            val qw = bb.float
            val qx = bb.float
            val qy = bb.float
            val qz = bb.float
            cloud.add(px, py, pz, sx, sy, sz, qw, qx, qy, qz, opacity, r, g, b)
        }
        return cloud
    }

    private fun readLine(stream: InputStream): String? {
        val builder = StringBuilder()
        while (true) {
            val value = stream.read()
            if (value < 0) return if (builder.isEmpty()) null else builder.toString()
            val ch = value.toChar()
            if (ch == '\n') return builder.toString()
            builder.append(ch)
        }
    }

    private fun readFully(stream: InputStream, buffer: ByteArray) {
        var offset = 0
        while (offset < buffer.size) {
            val read = stream.read(buffer, offset, buffer.size - offset)
            if (read < 0) throw EOFException("PLY 数据不足")
            offset += read
        }
    }
}